services: 
  scraper:
    build : "./scraper"
    ports: 
      - "5001:80"
    networks:
      - sub-etha

  backend :
    build : "./interviewprep"
    ports : 
      - "5000:5000"
    env_file: 
      - "./interviewprep/docker.development.env"
    depends_on: 
      - redis
    volumes:
      - type : volume
        source : api-volume
        target : /data/api-data
    networks:
      - sub-etha
  frontend :
    build : "./interviewprep/client"
    ports : 
      - "3000:80"
    volumes:
      - type : volume
        source : client-volume
        target : /data/client-data
    networks:
      - sub-etha
  nginx:
    build : "./nginx"
    ports :
      - "80:80"
    depends_on: 
      - frontend
      - backend
    networks:
      - sub-etha
  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes: 
      - type : volume
        source : redis-volume
        target : /data/redis-db
    networks:
      - sub-etha

volumes:  
  redis-volume:
  client-volume:
  api-volume:

networks:
  sub-etha: